// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.API.Data;

#nullable disable

namespace School.API.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20241216223056_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("School.API.models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateTime(1997, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "is.oscar@example.com",
                            Escolaridade = 1,
                            Nome = "Hytalo",
                            Sobrenome = "Pinheiro"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateTime(1962, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.francisca@example.com",
                            Escolaridade = 1,
                            Nome = "Maria",
                            Sobrenome = "Francisca"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
